(when (require 'auto-complete-config nil t)
  (global-auto-complete-mode t)
  (ac-config-default)
  (setq ac-expand-on-auto-complete nil)
  ;;(setq ac-use-menu-map t)
  (defun ac-quick-help-force ()
    (interactive)
    (ac-quick-help t))
  (define-key ac-completing-map (kbd "M-h") 'ac-quick-help-force)
  (define-key ac-complete-mode-map (kbd "C-n") 'ac-next)
  (define-key ac-complete-mode-map (kbd "C-p") 'ac-previous)
  (define-key ac-complete-mode-map (kbd "M-n") nil)
  (define-key ac-complete-mode-map (kbd "M-p") nil))
